<h1>  I AM DOING DEVOPS WITH MY HUBBY, I AM ONE BLESSED WOMAN </H1>
<h1> THANK YOU JESUS </H1>
<H1> docker image deployment </h1>

<h2> NOW AM ADDING FEW CHANGES TO MY DOCKER IMAGE AND SEE HOW AUTOMATION WILL GO FOR SECOND IMAGE</H2>
